# Example Dagster configuration for ClickHouse event log storage
# Optimized based on extensive performance testing

event_log_storage:
  module: dagster_clickhouse.event_log
  class: ClickHouseEventLogStorage
  config:
    # HTTP connection provides best performance (tested vs TCP)
    clickhouse_url: "http://dagster:dagster@localhost:8123/dagster"
    batch_size: 10000  # Optimized for maximum throughput (1M+ events/sec tested)
    flush_interval: 0.5  # Balanced latency/throughput (0.5s optimal)
    use_async_inserts: true  # CRITICAL: 17x better single-event performance
    connection_pool_size: 5  # Optimal concurrency for most workloads
    insert_timeout: 30.0  # Handles large batches reliably
    should_autocreate_tables: true

# Real-time streaming is built-in and uses Dagster's standard adaptive polling:
# - Starts at 250ms polling when events are active
# - Backs off to 16s when idle to save resources
# - Creates one thread per watched run for efficiency
# - Automatically cleans up when runs are no longer watched

# Alternative configurations based on performance testing:

# High-throughput batch processing (maximum events/sec):
# event_log_storage:
#   module: dagster_clickhouse.event_log
#   class: ClickHouseEventLogStorage
#   config:
#     clickhouse_url: "http://dagster:dagster@localhost:8123/dagster"
#     batch_size: 50000  # Large batches for maximum throughput
#     flush_interval: 0.5  # Optimal balance
#     use_async_inserts: true  # Essential for performance
#     connection_pool_size: 8  # Higher concurrency
#     should_autocreate_tables: true

# Low-latency streaming (minimum event delay):
# event_log_storage:
#   module: dagster_clickhouse.event_log
#   class: ClickHouseEventLogStorage
#   config:
#     clickhouse_url: "http://dagster:dagster@localhost:8123/dagster"
#     batch_size: 1000  # Small batches for low latency
#     flush_interval: 0.1  # Very frequent flushes
#     use_async_inserts: true  # Critical for single events
#     connection_pool_size: 5
#     should_autocreate_tables: true

# Memory-constrained environments:
# event_log_storage:
#   module: dagster_clickhouse.event_log
#   class: ClickHouseEventLogStorage
#   config:
#     clickhouse_url: "http://dagster:dagster@localhost:8123/dagster"
#     batch_size: 5000  # Moderate batch size
#     flush_interval: 1.0  # Less frequent flushes
#     use_async_inserts: true
#     connection_pool_size: 3  # Fewer connections
#     should_autocreate_tables: true
