# Example Dagster configuration for ClickHouse event log storage
# Optimized based on extensive performance testing

event_log_storage:
  module: dagster_clickhouse.event_log
  class: ClickHouseEventLogStorage
  config:
    clickhouse_url: "clickhouse://dagster:dagster@localhost:8123/dagster"  # HTTP for best performance
    batch_size: 100           # Small batches for balanced latency/throughput
    flush_interval: 1       # Quick flushing (100ms) for responsive UI
    use_async_inserts: true   # CRITICAL: 17x performance boost
    connection_pool_size: 100   # Optimal concurrency
    insert_timeout: 10.0      # Handles large batches
