name: Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
      
    - name: Set up Python
      run: uv python install
      
    - name: Install dependencies
      run: uv sync --dev
      
    - name: Run ruff check
      run: uv run ruff check . --output-format=github
      
    - name: Run ruff format check
      run: uv run ruff format --check .
      
    - name: Run black check
      run: uv run black --check --diff .
      
    - name: Run mypy
      run: uv run mypy dagster_clickhouse/
      continue-on-error: true  # Don't fail CI on mypy errors initially
