name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    services:
      clickhouse:
        image: clickhouse/clickhouse-server:latest
        ports:
          - 8123:8123
          - 9000:9000
        env:
          CLICKHOUSE_DB: dagster
          CLICKHOUSE_USER: dagster
          CLICKHOUSE_PASSWORD: dagster
          CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
        options: >-
          --health-cmd "clickhouse-client --query 'SELECT 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 30s

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync --all-extras --dev

    - name: Wait for ClickHouse to be ready
      run: |
        timeout 60 bash -c 'until curl -s http://localhost:8123/ping; do sleep 2; done'
        echo "ClickHouse is ready"

    - name: Test ClickHouse connection
      run: |
        curl -s "http://dagster:dagster@localhost:8123/?query=SELECT%201" || echo "Connection test failed"

    - name: Run tests
      run: uv run pytest tests/ -v --cov=dagster_clickhouse --cov-report=xml --cov-report=term
      env:
        # Use localhost for tests since we're running in the same network
        CLICKHOUSE_URL: "http://dagster:dagster@localhost:8123/dagster"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
